# Generated by Django 3.0.6 on 2021-12-21 17:15

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(choices=[('Italian Suits', 'Italian Suits'), ('Turkish Suits', 'Turkish Suits'), ('Chinese Suits', 'Chinese Suits'), ('Italian Shoes', 'Italian Shoes'), ('Turkish Shoes', 'Turkish Shoes'), ('Chinese Shoes', 'Chinese Shoes')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.IntegerField(choices=[(38, 38), (40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (64, 64), (66, 66), (68, 68), (70, 70)], db_index=True, default=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
