# Generated by Django 3.1.7 on 2022-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220725_1018'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Sub_Category',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(db_index=True, max_length=100)),
        #         ('slug', models.SlugField(max_length=200, unique=True)),
        #     ],
        #     options={
        #         'verbose_name': 'sub_category',
        #         'verbose_name_plural': 'sub_categories',
        #         'ordering': ('name',),
        #     },
        # ),
        migrations.CreateModel(
            name='Suits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('sizes', models.IntegerField(choices=[(40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (64, 64), (66, 66), (68, 68), (70, 70)], db_index=True, default=40, null=True)),
                ('brands', models.CharField(choices=[('Italian Suits', 'Italian Suits'), ('Turkish Suits', 'Turkish Suits'), ('Chinese Suits', 'Chinese Suits'), ('Italian Shoes', 'Italian Shoes'), ('Turkish Shoes', 'Turkish Shoes'), ('Chinese Shoes', 'Chinese Shoes')], db_index=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
