# Generated by Django 3.0.6 on 2021-12-22 09:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('shop', '0004_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('sizes', models.IntegerField(choices=[(40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (64, 64), (66, 66), (68, 68), (70, 70)], db_index=True, default=40, null=True)),
                ('brands', models.CharField(choices=[('Italian Suits', 'Italian Suits'), ('Turkish Suits', 'Turkish Suits'), ('Chinese Suits', 'Chinese Suits'), ('Italian Shoes', 'Italian Shoes'), ('Turkish Shoes', 'Turkish Shoes'), ('Chinese Shoes', 'Chinese Shoes')], db_index=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Suits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('sizes', models.IntegerField(choices=[(40, 40), (42, 42), (44, 44), (46, 46), (48, 48), (50, 50), (52, 52), (54, 54), (56, 56), (58, 58), (60, 60), (64, 64), (66, 66), (68, 68), (70, 70)], db_index=True, default=40, null=True)),
                ('brands', models.CharField(choices=[('Italian Suits', 'Italian Suits'), ('Turkish Suits', 'Turkish Suits'), ('Chinese Suits', 'Chinese Suits'), ('Italian Shoes', 'Italian Shoes'), ('Turkish Shoes', 'Turkish Shoes'), ('Chinese Shoes', 'Chinese Shoes')], db_index=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AddField(
            model_name='suits',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suits_products', to='shop.Category'),
        ),
        migrations.AddField(
            model_name='suits',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_products', to='shop.Category'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterIndexTogether(
            name='suits',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='shoes',
            index_together={('id', 'slug')},
        ),
    ]
