# Generated by Django 3.0.6 on 2021-12-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211223_1429'),
        ('shop', '0006_auto_20211222_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
